import Head from 'next/head'
import Appbar from '../components/Appbar'
import Selection from '../components/selection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Q-A App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Appbar />
      <Selection />
    </div>
  )
}
